"""
Centralized option registry for llama.cpp server CLI options.
Each entry: (label, default, widget_type, choices_or_params, sub_keys, help_text)
"""


def get_option(key):
    """Get option tuple by key. Returns None if not found."""
    return _OPTIONS.get(key)


def iter_options():
    """Iterate all option key -> tuple."""
    yield from _OPTIONS.items()


# Widget types: 'file', 'dropdown', 'checkbox', 'radio', 'spin',
#               'float_spin', 'text', 'panel_header'

_OPTIONS = {
    # === MODEL ===
    'model': ('Model (-m)', '', 'file', None, None,
              'Path to the model GGUF file to load.'),
    'lora': ('LoRA Adapter', '', 'file', None, None,
             'Path to a LoRA adapter (comma-separated for multiple).'),
    'lora_scaled': ('LoRA Scale', 1.0, 'float_spin', (0.0, 10.0, 0.05), None,
                    'LoRA adapter with user-defined scaling (FNAME:SCALE).'),
    'mmproj': ('MMProj', '', 'file', None, None,
               'Path to a multimodal projector file.'),
    'no_mmproj': ('No MMProj Auto', False, 'checkbox', None, None,
                  'Disable automatic download of mmproj.'),
    'no_mmproj_offload': ('No MMProj Offload', False, 'checkbox', None, None,
                          'Disable GPU offloading for multimodal projector.'),
    'image': ('Image', '', 'file', None, None,
              'Path to an image file for multimodal models.'),
    'audio': ('Audio', '', 'file', None, None,
              'Path to an audio file for multimodal models.'),
    'video': ('Video', '', 'file', None, None,
              'Path to a video file for multimodal models.'),
    'mtmd_batch_max_tokens': ('MTMD Batch Max Tokens', 1024, 'spin', (0, 65536, 64), None,
                              'Max image tokens per batch when encoding images.'),
    'mlock': ('MLock', False, 'checkbox', None, None,
              'Force system to keep model in RAM, preventing swapping.'),
    'mmap': ('MMap', True, 'checkbox', None, None,
             'Memory-map the model file. Disabling speeds load but may increase pageouts.'),
    'direct_io': ('Direct IO', False, 'checkbox', None, None,
                  'Use DirectIO if available on the filesystem.'),
    'check_tensors': ('Check Tensors', False, 'checkbox', None, None,
                      'Check model tensor data for invalid values on load.'),
    'tags': ('Tags', '', 'text', None, None,
             'Set model tags, comma-separated (informational).'),
    'alias': ('Alias', '', 'text', None, None,
              'Set model name aliases, comma-separated (used by API).'),
    'override_kv': ('Override KV', '', 'text', None, None,
                    'Override model metadata: KEY=TYPE:VALUE,...'),
    'lora_init_without_apply': ('LoRA Init W/O Apply', False, 'checkbox', None, None,
                                'Load LoRA adapters without applying them.'),
    # === GPU ===
    'gpu_layers': ('GPU Layers', 0, 'spin', (0, 1000, 1), None,
                   'Number of layers to offload to GPU. 0 = CPU only.'),
    'split_mode': ('Split Mode', 'layer', 'dropdown',
                   ['none', 'layer', 'row', 'tensor'], None,
                   'How to split the model across multiple GPUs.'),
    'tensor_split': ('Tensor Split', '', 'text', None, None,
                     'Fractions of model per GPU, comma-separated (e.g. 3,1).'),
    'main_gpu': ('Main GPU', 0, 'spin', (0, 16, 1), None,
                 'GPU index for the model or intermediate results.'),
    'device': ('Device', '', 'text', None, None,
               'Comma-separated devices for offloading.'),
    'rpc': ('RPC', '', 'text', None, None,
            'Comma-separated RPC servers (host:port).'),
    'cpu_moe': ('CPU MoE', False, 'checkbox', None, None,
                'Keep all MoE weights on CPU.'),
    'n_cpu_moe': ('N CPU MoE', 0, 'spin', (0, 128, 1), None,
                  'Keep MoE weights of first N layers on CPU.'),
    'fit': ('Fit', True, 'checkbox', None, None,
            'Adjust unset arguments to fit in device memory.'),
    'fit_print': ('Fit Print', '', 'text', None, None,
                  'Print estimated memory requirements.'),
    'fit_target': ('Fit Target', '', 'text', None, None,
                   'Target memory margin per device for --fit.'),
    'fit_ctx': ('Fit CTX', 4096, 'spin', (256, 131072, 64), None,
                'Minimum context size settable by --fit.'),
    # === CACHE ===
    'cache_prompt': ('Cache Prompt', True, 'checkbox', None, None,
                     'Enable prompt caching across requests.'),
    'cache_reuse': ('Cache Reuse', 0, 'spin', (0, 1000, 1), None,
                    'Min chunk size for KV cache reuse via shifting.'),
    'cache_ram': ('Cache RAM (MiB)', 8192, 'spin', (0, 65536, 64), None,
                  'Maximum prompt cache size in MiB.'),
    'cache_type_k': ('Cache Type K', 'f16', 'dropdown',
                     ['f16', 'f32', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'], None,
                     'KV cache data type for K.'),
    'cache_type_v': ('Cache Type V', 'f16', 'dropdown',
                     ['f16', 'f32', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'], None,
                     'KV cache data type for V.'),
    'kv_unified': ('KV Unified', False, 'checkbox', None, None,
                   'Share a unified KV buffer across all sequences.'),
    'cache_idle_slots': ('Cache Idle Slots', True, 'checkbox', None, None,
                          'Save idle slots to the prompt cache on new task, and clear them when using unified KV.'),
    'slot_save_path': ('Slot Save Path', '', 'file', None, None,
                       'Path to save slot KV cache to disk.'),
    'ctx_checkpoints': ('CTX Checkpoints', 32, 'spin', (0, 256, 1), None,
                        'Max number of checkpoints per slot.'),
    'checkpoint_min_step': ('Checkpoint Min Step', 256, 'spin',
                            (0, 65536, 1), None,
                            'Minimum spacing between context checkpoints in tokens (0 = no minimum).'),
    # === CONTEXT ===
    'ctx_size': ('Context Size', 0, 'spin', (0, 131072, 1), None,
                 'Size of the prompt context. 0 = loaded from model.'),
    'batch_size': ('Batch Size', 2048, 'spin', (1, 8192, 1), None,
                   'Logical maximum batch size.'),
    'ubatch_size': ('UBatch Size', 512, 'spin', (1, 8192, 1), None,
                    'Physical maximum batch size.'),
    'predict': ('Predict', -1, 'spin', (-1, 4096, 1), None,
                'Number of tokens to predict. -1 = infinity.'),
    'keep': ('Keep', 0, 'spin', (-1, 131072, 1), None,
             'Tokens to keep from the initial prompt. -1 = all.'),
    'swa_full': ('SWA Full', False, 'checkbox', None, None,
                 'Use full-size sliding-window attention cache.'),
    # === CPU ===
    'threads': ('Threads', 0, 'spin', (0, 256, 1), None,
                'Number of CPU threads for generation.'),
    'threads_batch': ('Threads Batch', 0, 'spin', (0, 256, 1), None,
                      'Threads for batch and prompt processing.'),
    'cpu_mask': ('CPU Mask', '', 'text', None, None,
                 'CPU affinity mask (hex). Complements cpu-range.'),
    'cpu_range': ('CPU Range', '', 'text', None, None,
                  'Range of CPUs for affinity (lo-hi).'),
    'cpu_strict': ('CPU Strict', False, 'checkbox', None, None,
                   'Use strict CPU placement.'),
    'prio': ('Priority', 0, 'spin', (0, 5, 1), None,
             'Process/thread priority level.'),
    'poll': ('Poll', 2, 'spin', (0, 4, 1), None,
             'Polling level to wait for work. 0 = no polling.'),
    'prio_prompt': ('Prio Prompt', 0, 'spin', (0, 5, 1), None,
                    'Priority for prompt processing threads.'),
    'prio_predict': ('Prio Predict', 0, 'spin', (0, 5, 1), None,
                     'Priority for prediction threads.'),
    'prio_batch': ('Prio Batch', 0, 'spin', (0, 5, 1), None,
                   'Priority for batch processing threads.'),
    'prio_draft': ('Prio Draft', 0, 'spin', (0, 5, 1), None,
                   'Priority for speculative decoding draft threads.'),
    # === ROPE ===
    'rope_scaling': ('RoPE Scaling', 'none', 'dropdown',
                     ['none', 'linear', 'yarn'], None,
                     'RoPE frequency scaling method.'),
    'rope_scale': ('RoPE Scale', 1.0, 'float_spin', (0.01, 128.0, 0.01),
                   None, 'RoPE context scaling factor.'),
    'rope_freq_base': ('RoPE Freq Base', 0.0, 'float_spin',
                       (0.0, 1000000.0, 100.0), None,
                       'RoPE base frequency for NTK-aware scaling.'),
    'rope_freq_scale': ('RoPE Freq Scale', 1.0, 'float_spin',
                        (-5.0, 5.0, 0.05), None,
                        'RoPE frequency scaling factor (1/N).'),
    'yarn_orig_ctx': ('YARN Orig CTX', 0, 'spin', (0, 131072, 1), None,
                      'YaRN: original context size during model training.'),
    'yarn_ext_factor': ('YARN Ext Factor', -0.0, 'float_spin',
                        (-2.0, 2.0, 0.01), None,
                        'YaRN: extrapolation mix factor.'),
    'yarn_attn_factor': ('YARN Attn Factor', 1.0, 'float_spin',
                         (0.0001, 128.0, 0.0001), None,
                         'YaRN: attention magnitude scale.'),
    'yarn_beta_fast': ('YARN Beta Fast', 32.0, 'float_spin',
                       (1.0, 4096.0, 1.0), None,
                       'YaRN: low correction dim (beta).'),
    'yarn_beta_slow': ('YARN Beta Slow', 1.0, 'float_spin',
                       (1.0, 4096.0, 1.0), None,
                       'YaRN: high correction dim (alpha).'),
    'grp_attn_n': ('Group Attn N', 1, 'spin', (1, 1024, 1), None,
                   'Group-attention factor.'),
    'grp_attn_w': ('Group Attn W', 512, 'spin', (1, 1024, 1), None,
                   'Group-attention width.'),
    'flash_attn': ('Flash Attn', 'auto', 'dropdown',
                   ['auto', 'on', 'off'], None,
                   'Use Flash Attention.'),
    # === SAMPLING ===
    'temperature': ('Temperature', 0.8, 'float_spin', (0.0, 5.0, 0.01),
                    None, 'Sampling temperature. Higher = more random.'),
    'top_k': ('Top K', 40, 'spin', (1, 100, 1), None,
              'Top-k sampling. 0 = disabled.'),
    'top_p': ('Top P', 0.95, 'float_spin', (0.0, 1.0, 0.01), None,
              'Top-p (nucleus) sampling. 1.0 = disabled.'),
    'min_p': ('Min P', 0.05, 'float_spin', (0.0, 1.0, 0.01), None,
              'Min-p sampling. 0.0 = disabled.'),
    'top_n_sigma': ('Top N Sigma', -1.0, 'float_spin', (-1.0, 10.0, 0.1),
                    None, 'Top-n-sigma sampling. -1.0 = disabled.'),
    'xtc_prob': ('XTC Prob', 0.0, 'float_spin', (0.0, 1.0, 0.01), None,
                 'XTC probability. 0.0 = disabled.'),
    'xtc_threshold': ('XTC Threshold', 0.1, 'float_spin', (0.01, 1.0, 0.01),
                      None, 'XTC threshold. 1.0 = disabled.'),
    'typical': ('Typical P', 1.0, 'float_spin', (0.0, 2.0, 0.01), None,
                'Locally typical sampling parameter p. 1.0 = disabled.'),
    'adaptive_target': ('Adaptive Target', 0.5, 'float_spin', (0.0, 1.0, 0.01),
                        None, 'Adaptive-p target probability.'),
    'adaptive_decay': ('Adaptive Decay', 16.0, 'float_spin',
                       (1.0, 256.0, 1.0), None,
                       'Adaptive-p decay rate. Lower = more reactive.'),
    'dynatemp_range': ('DynTemp Range', 0.0, 'float_spin', (0.0, 5.0, 0.01),
                       None, 'Dynamic temperature range. 0.0 = disabled.'),
    'dynatemp_exp': ('DynTemp Exp', 1.0, 'float_spin', (0.0, 5.0, 0.01),
                     None, 'Dynamic temperature exponent.'),
    'seed': ('Seed', 0, 'spin', (-1, 2147483647, 1), None,
             'RNG seed. -1 = random seed.'),
    'samplers': ('Samplers', 'xyzc', 'text', None, None,
                 'Sampler order, separated by ;'),
    'sampler_seq': ('Sampler Seq', 0, 'spin', (0, 100000, 1), None,
                    'Simplified sampler sequence string.'),
    # === MIROSTAT ===
    'mirostat': ('Mirostat', 0, 'radio', [0, 1, 2], None,
                 'Mirostat sampling mode. 0=off, 1=Mirostat, 2=Mirostat 2.0'),
    'mirostat_lr': ('Mirostat LR', 0.1, 'float_spin', (0.001, 1.0, 0.001),
                    None, 'Mirostat learning rate (eta).'),
    'mirostat_ent': ('Mirostat Ent', 5.0, 'float_spin', (0.0, 15.0, 0.1),
                     None, 'Mirostat target entropy (tau).'),
    # === PENALTIES ===
    'repeat_last_n': ('Repeat Last N', 64, 'spin', (0, 256, 1), None,
                      'Last N tokens to consider for penalties.'),
    'repeat_penalty': ('Repeat Penalty', 1.0, 'float_spin', (0.0, 5.0, 0.01),
                       None, 'Penalty for repeating token sequences.'),
    'presence_penalty': ('Presence Penalty', 0.0, 'float_spin',
                         (-2.0, 2.0, 0.01), None,
                         'Presence penalty (positive = discourage repetition).'),
    'frequency_penalty': ('Frequency Penalty', 0.0, 'float_spin',
                          (-2.0, 2.0, 0.01), None,
                          'Frequency penalty based on token frequency.'),
    'ignore_eos': ('Ignore EOS', False, 'checkbox', None, None,
                   'Ignore end-of-stream token and continue generating.'),
    # === DRY ===
    'dry_multiplier': ('DRY Multiplier', 1.1, 'float_spin', (0.0, 10.0, 0.01),
                       None, 'DRY sampling multiplier. 0.0 = disabled.'),
    'dry_base': ('DRY Base', 1.0, 'float_spin', (0.0, 10.0, 0.01), None,
                 'DRY sampling base value.'),
    'dry_allowed_length': ('DRY Allowed Length', 0, 'spin', (0, 1000, 1),
                           None, 'Allowed length for DRY sampling.'),
    'dry_penalty_last_n': ('DRY Penalty Last N', -1, 'spin', (-1, 2048, 1),
                           None, 'DRY penalty window size.'),
    'dry_sequence_breaker': ('DRY Seq Breaker', '', 'text', None, None,
                             'Sequence breaker chars for DRY sampling.'),
    # === GRAMMAR ===
    'logit_bias': ('Logit Bias', '', 'text', None, None,
                   'Modify token likelihood: TOKEN_ID(+/-)BIAS'),
    'grammar': ('Grammar', '', 'text', None, None,
                'BNF-like grammar to constrain generation.'),
    'grammar_file': ('Grammar File', '', 'file', None, None,
                     'File containing a BNF grammar.'),
    'grammar': ('Grammar', '', 'multiline_text', None, None,
                'BNF-like grammar to constrain generation.'),
    'json_schema': ('JSON Schema', '', 'multiline_text', None, None,
                    'JSON schema to constrain generation.'),
    'json_schema_file': ('JSON Schema File', '', 'file', None, None,
                          'File containing a JSON schema.'),
    # === SPECULATIVE ===
    # Master type selector
    'spec_type': ('Spec Type', 'none', 'ordered_list_of_options',
                  ['ngram-simple', 'ngram-map-k', 'ngram-map-k4v',
                   'ngram-mod', 'ngram-cache', 'draft-simple',
                   'draft-eagle3', 'draft-mtp'], None,
                  'Speculative decoding type(s) in priority order. '
                  'Use Add/Remove/Reorder to compose the list.'),
    # Draft model flags (draft-simple, draft-eagle3, draft-mtp)
    'spec_draft_n_max': ('Draft N Max', 16, 'spin', (0, 256, 1), None,
                         'Max draft tokens per step (draft models only).'),
    'spec_draft_n_min': ('Draft N Min', 0, 'spin', (0, 256, 1), None,
                         'Min draft tokens per step (draft models only).'),
    'spec_draft_model': ('Draft Model', '', 'file', None, None,
                         'Draft model for speculative decoding.'),
    'spec_draft_hf': ('Draft HF Repo', '', 'text', None, None,
                      'HuggingFace repo for draft model (user/model[:quant]).'),
    'spec_draft_threads': ('Draft Threads', 0, 'spin', (0, 256, 1), None,
                           'CPU threads for draft model. 0 = auto.'),
    'spec_draft_threads_batch': ('Draft Threads Batch', 0, 'spin', (0, 256, 1), None,
                                 'Batch threads for draft model. 0 = auto.'),
    'spec_draft_cpu_mask': ('Draft CPU Mask', '', 'text', None, None,
                            'CPU affinity mask for draft model (hex).'),
    'spec_draft_cpu_range': ('Draft CPU Range', '', 'text', None, None,
                             'CPU range for draft model (lo-hi).'),
    'spec_draft_cpu_strict': ('Draft CPU Strict', False, 'checkbox', None, None,
                              'Strict CPU placement for draft model.'),
    'spec_draft_prio': ('Draft Priority', 0, 'spin', (0, 3, 1), None,
                        'Process priority for draft threads.'),
    'spec_draft_poll': ('Draft Poll', 2, 'spin', (0, 4, 1), None,
                        'Polling level for draft model.'),
    'spec_draft_type_k': ('Draft Cache Type K', 'f16', 'dropdown',
                          ['f16', 'f32', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'], None,
                          'KV cache type for draft model K.'),
    'spec_draft_type_v': ('Draft Cache Type V', 'f16', 'dropdown',
                          ['f16', 'f32', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'], None,
                          'KV cache type for draft model V.'),
    'spec_draft_cpu_moe': ('Draft CPU MoE', False, 'checkbox', None, None,
                           'Keep draft MoE weights on CPU.'),
    'spec_draft_n_cpu_moe': ('Draft N CPU MoE', 0, 'spin', (0, 128, 1), None,
                             'Keep draft MoE weights of first N layers on CPU.'),
    'spec_draft_override_tensor': ('Draft Override Tensor', '', 'text', None, None,
                                   'Override tensor buffer type for draft model.'),
    'spec_draft_device': ('Draft Device', '', 'text', None, None,
                          'Device(s) for draft model offloading.'),
    'spec_draft_ngl': ('Draft NGL', 0, 'spin', (0, 200, 1), None,
                       'GPU layers for draft model.'),
    'spec_draft_backend_sampling': ('Draft Backend Sampling', True, 'checkbox', None, None,
                                    'Offload draft sampling to the backend.'),
    'spec_draft_p_split': ('Draft P Split', 0.1, 'float_spin',
                           (0.0, 1.0, 0.01), None,
                           'Speculative decoding split probability.'),
    'spec_draft_p_min': ('Draft P Min', 0.0, 'float_spin', (0.0, 1.0, 0.01),
                         None, 'Min draft probability (greedy).'),
    # Ngram-mod flags (ngram-mod)
    'spec_ngram_mod_n_min': ('Ngram Mod N Min', 48, 'spin', (0, 1024, 1), None,
                             'Min n-gram length for ngram-mod.'),
    'spec_ngram_mod_n_max': ('Ngram Mod N Max', 64, 'spin', (0, 1024, 1), None,
                             'Max n-gram length for ngram-mod.'),
    'spec_ngram_mod_n_match': ('Ngram Mod N Match', 24, 'spin', (1, 1024, 1), None,
                               'Number of matching tokens for ngram-mod.'),
    # Ngram-simple flags (ngram-simple)
    'spec_ngram_simple_size_n': ('Ngram Simple Size N', 12, 'spin', (1, 1024, 1), None,
                                 'N-gram size for ngram-simple.'),
    'spec_ngram_simple_size_m': ('Ngram Simple Size M', 48, 'spin', (1, 1024, 1), None,
                                 'M-gram size for ngram-simple.'),
    'spec_ngram_simple_min_hits': ('Ngram Simple Min Hits', 1, 'spin', (1, 256, 1), None,
                                   'Min hits for ngram-simple.'),
    # Ngram-map-k flags (ngram-map-k)
    'spec_ngram_map_k_size_n': ('Ngram Map-K Size N', 12, 'spin', (1, 1024, 1), None,
                                'N-gram size for ngram-map-k.'),
    'spec_ngram_map_k_size_m': ('Ngram Map-K Size M', 48, 'spin', (1, 1024, 1), None,
                                'M-gram size for ngram-map-k.'),
    'spec_ngram_map_k_min_hits': ('Ngram Map-K Min Hits', 1, 'spin', (1, 256, 1), None,
                                  'Min hits for ngram-map-k.'),
    # Ngram-map-k4v flags (ngram-map-k4v)
    'spec_ngram_map_k4v_size_n': ('Ngram Map-K4V Size N', 12, 'spin', (1, 1024, 1), None,
                                  'N-gram size for ngram-map-k4v.'),
    'spec_ngram_map_k4v_size_m': ('Ngram Map-K4V Size M', 48, 'spin', (1, 1024, 1), None,
                                  'M-gram size for ngram-map-k4v.'),
    'spec_ngram_map_k4v_min_hits': ('Ngram Map-K4V Min Hits', 1, 'spin', (1, 256, 1), None,
                                    'Min hits for ngram-map-k4v.'),
    # Ngram-cache flags (ngram-cache)
    'lookup_cache_static': ('Lookup Cache Static', '', 'file', None, None,
                            'Static lookup cache file for ngram-cache.'),
    'lookup_cache_dynamic': ('Lookup Cache Dynamic', '', 'file', None, None,
                             'Dynamic lookup cache file for ngram-cache.'),
    # === PROMPT ===
    'prompt': ('Prompt', '', 'multiline_text', None, None,
               'Prompt text to start generation.'),
    'system_prompt': ('System Prompt', '', 'multiline_text', None, None,
                      'System prompt for chat templates.'),
    'file': ('File (-f)', '', 'file', None, None,
             'File containing the prompt.'),
    'in_file': ('Input File', '', 'file', None, None,
                'Input file (comma-separated for multiple).'),
    'binary_file': ('Binary File', '', 'file', None, None,
                    'Binary file containing the prompt.'),
    'reverse_prompt': ('Reverse Prompt', '', 'text', None, None,
                       'Halt generation at this prompt in interactive mode.'),
    'escape': ('Escape', False, 'checkbox', None, None,
               'Process escape sequences in input.'),
    'special': ('Special', False, 'checkbox', None, None,
                'Enable special token output.'),
    'interactive': ('Interactive', False, 'checkbox', None, None,
                    'Run in interactive mode.'),
    'interactive_first': ('Interactive First', False, 'checkbox', None, None,
                          'Interactive mode, wait for input immediately.'),
    'multiline_input': ('Multiline Input', False, 'checkbox', None, None,
                        'Allow pasting multiple lines without escaping.'),
    'in_prefix': ('Input Prefix', '', 'text', None, None,
                  'String to prefix user inputs with.'),
    'in_suffix': ('Input Suffix', '', 'text', None, None,
                  'String to suffix after user inputs.'),
    'warmup': ('Warmup', True, 'checkbox', None, None,
               'Perform warmup with an empty run.'),
    'perf': ('Perf', False, 'checkbox', None, None,
             'Enable internal performance timings.'),
    # === CHAT ===
    'chat_template': ('Chat Template', '', 'text', None, None,
                      'Custom Jinja chat template string.'),
    'chat_template_file': ('Chat Template File', '', 'file', None, None,
                           'File with custom Jinja chat template.'),
    'reasoning_format': ('Reasoning Format', '', 'dropdown',
                         ['none', 'openai', 'deepseek'], None,
                         'How to handle model reasoning/thinking tokens.'),
    'reasoning_budget': ('Reasoning Budget', '', 'text', None, None,
                         'Token budget for thinking, -1=unrestricted.'),
    'jinja': ('Jinja', True, 'checkbox', None, None,
              'Use Jinja2 template engine for chat formatting.'),
    'prefill_assistant': ('Prefill Assistant', True, 'checkbox', None, None,
                          'Prefill assistant response for continued chats.'),
    # === DISPLAY ===
    'verbose_prompt': ('Verbose Prompt', False, 'checkbox', None, None,
                       'Print verbose prompt before generation.'),
    'display_prompt': ('Display Prompt', True, 'checkbox', None, None,
                       'Print prompt during generation.'),
    'color': ('Color', 'auto', 'dropdown', ['on', 'off', 'auto'], None,
              'Colorize output. auto = color when terminal.'),
    'slot_prompt_similarity': ('Slot Sim.', 0.1, 'float_spin',
                               (0.0, 1.0, 0.01), None,
                               'Prompt similarity threshold for slot reuse.'),
    'simple_io': ('Simple IO', False, 'checkbox', None, None,
                  'Basic I/O for subprocess/limited consoles.'),
    'show_timings': ('Show Timings', True, 'checkbox', None, None,
                     'Show timing info after each response.'),
    # === SERVER ===
    'host': ('Host', '127.0.0.1', 'text', None, None,
             'IP address to listen on.'),
    'port': ('Port', 8080, 'spin', (0, 65535, 1), None,
             'Port to listen on.'),
    'parallel': ('Parallel', 4, 'spin', (1, 128, 1), None,
                 'Number of server slots / parallel sequences.'),
    'sequences': ('Sequences', 2, 'spin', (1, 64, 1), None,
                  'Number of parallel decode sequences.'),
    'cont_batching': ('Cont Batching', False, 'checkbox', None, None,
                      'Enable continuous (dynamic) batching.'),
    'timeout': ('Timeout (s)', 3600, 'spin', (0, 36000, 1), None,
                'Server read/write timeout in seconds.'),
    'sse_ping_interval': ('SSE Ping Interval', 30, 'spin', (-1, 36000, 1), None,
                          'SSE ping interval in seconds (-1 = disabled).'),
    'threads_http': ('Threads HTTP', -1, 'spin', (-1, 128, 1), None,
                     'Threads for HTTP request processing.'),
    'api_key': ('API Key', '', 'text', None, None,
                'API key(s) for authentication, comma-separated.'),
    'ssl_key': ('SSL Key', '', 'file', None, None,
                'PEM-encoded SSL private key file.'),
    'ssl_cert': ('SSL Cert', '', 'file', None, None,
                 'PEM-encoded SSL certificate file.'),
    'path': ('Path', '', 'text', None, None,
             'Path to serve static files from.'),
    'api_prefix': ('API Prefix', '', 'text', None, None,
                   'Prefix path for the server API.'),
    'ui': ('UI', True, 'checkbox', None, None,
           'Enable the Web UI interface.'),
    'ui_config': ('UI Config', '', 'text', None, None,
                  'JSON with default UI settings.'),
    'ui_mcp_proxy': ('UI MCP Proxy', False, 'checkbox', None, None,
                     'Enable MCP CORS proxy - do not enable in untrusted environments (experimental).'),
    'agent': ('Agent Mode', False, 'checkbox', None, None,
              'Enable CORS proxy and all built-in tools - do not enable in untrusted environments (experimental).'),
    'tools': ('Tools', False, 'checkbox', None, None,
              'Enable built-in tools for AI agents. Tools: read_file, file_glob_search, grep_search, exec_shell_command, write_file, edit_file, apply_diff, get_datetime.'),
    'embedding': ('Embedding', False, 'checkbox', None, None,
                  'Restrict to embedding-only mode.'),
    'rerank': ('Rerank', False, 'checkbox', None, None,
               'Enable the reranking endpoint.'),
    'metrics': ('Metrics', False, 'checkbox', None, None,
                'Enable Prometheus metrics endpoint.'),
    'props': ('Props', False, 'checkbox', None, None,
              'Allow changing properties via POST /props.'),
    'slots': ('Slots', True, 'checkbox', None, None,
              'Expose slots monitoring endpoint.'),
    # === EMBEDDING ===
    'pooling': ('Pooling', '', 'dropdown',
                ['none', 'rank', 'retrieval', 'embedding', 'any'], None,
                'Pooling type for embedding models.'),
    'attention': ('Attention', '', 'dropdown',
                  ['none', 'bidirectional', 'causal', 'any'], None,
                  'Attention type for embedding models.'),
    # === LOG ===
    'log_file': ('Log File', '', 'file', None, None,
                 'Write server logs to file.'),
    'log_prompts_dir': ('Log Prompts Dir', '', 'file', None, None,
                        'Directory to log prompts (debugging).'),
    'log_colors': ('Log Colors', 'auto', 'dropdown',
                   ['on', 'off', 'auto'], None,
                   'Colorize log output. auto = color when terminal.'),
    'log_verbosity': ('Log Verbosity', 3, 'spin', (0, 5, 1), None,
                      'Log verbosity threshold (0=off, 1=error, 2=warn, 3=info, 4=debug, 5=trace).'),
    'log_prefix': ('Log Prefix', True, 'checkbox', None, None,
                   'Include source file/line prefix in log lines.'),
    'log_timestamps': ('Log Timestamps', True, 'checkbox', None, None,
                       'Include timestamps in log lines.'),
    'log_disable': ('Log Disable', False, 'checkbox', None, None,
                    'Disable all logging.'),
    # === PANEL HEADERS (UI-only grouping) ===
    'spec_panel': ('Speculative', False, 'panel_header', None,
                   ['spec_draft_model', 'spec_type', 'spec_draft_n_max',
                    'spec_draft_n_min', 'spec_draft_backend_sampling',
                    'spec_draft_p_split', 'spec_draft_p_min',
                    'spec_draft_device', 'spec_draft_ngl'],
                   'Speculative decoding options.'),
    'chat_panel': ('Chat Template', True, 'panel_header', None,
                   ['chat_template', 'chat_template_file',
                    'reasoning_format', 'reasoning_budget',
                    'jinja', 'prefill_assistant'],
                   'Chat template and formatting options.'),
    'display_panel': ('Display', True, 'panel_header', None,
                      ['verbose_prompt', 'display_prompt', 'color',
                       'slot_prompt_similarity', 'simple_io', 'show_timings'],
                      'Display and output options.'),
    'ui_panel': ('UI', True, 'panel_header', None,
                 ['ui', 'ui_config', 'ui_mcp_proxy'],
                 'Web UI settings.'),
    'server_features_panel': ('Server Features', False, 'panel_header', None,
                                ['agent', 'tools', 'embedding', 'rerank', 'metrics',
                                 'props', 'slots'],
                               'Optional server endpoint features.'),
    'log_panel': ('Log', True, 'panel_header', None,
                  ['log_file', 'log_colors', 'log_verbosity',
                   'log_prefix', 'log_timestamps', 'log_disable'],
                  'Log output configuration.'),
}
